# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven
on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: /myapp
    defaults:
      run:
        working-directory: ./myapp
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        version-patch: true
    # - name: Release
    #   uses: qcastel/github-actions-maven-release@master
    #   with:
    #       version-patch: true
    # - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: clean maven
      run: mvn clean

    - name: change jar version
      run: mvn build-helper:parse-version versions:set -DnewVersion=${MAVEN_PROJECT_VERSION}

    - name: Build with Maven
      run: mvn compile

    - name: Package with maven
      run: mvn package
   
    - name: Create artifact
      run: mvn --batch-mode deploy
    #   run: mkdir artifact && cp target/*.jar artifact
    
    # - uses: actions/upload-artifact@v2
    #   with:
    #     name: Package
    #     path: artifact

    # - name: Run the Maven verify phase
    #   run: mvn --batch-mode --update-snapshots verify